export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_SHIRT = 'SET_SHIRT';
export const SET_LOADING = 'SET_LOADING';
export const SET_QUERY = 'SET_QUERY';

// LOADING
export const TOGGLE_LOADING = 'TOGGLE_LOADING';